### PR TITLE
fix: Logic for naming objects at destination

### LINKED ISSUE #169: AzureStorageDataSinkFactory relies on Source properties
# Bug Report

## Describe the Bug

During a multi object transfer process, when the `DataSource` is not `AzureStorage`, an issue arises if the `Consumer` defines a `blobName` in the destination. In this scenario, all objects are overwritten using the same file name, resulting in data loss or unintended overwriting. This occurs due to the reliance of the `AzureStorageDataSinkFactory` on `DataSource` specifics, particularly the `blobPrefix` property, which is further utilized to determine object naming, if the property is present it would mean it is a multi object transfer, but it is true only if the `DataSource` is `AzureStorage`.

`AzureStorageDataSinkFactory`:
https://github.com/eclipse-edc/Technology-Azure/blob/fdbc521750959868cf1ff6c93230e6220ba8ab70/extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactory.java#L77-L88

`AzureStorageDataSink`:
https://github.com/eclipse-edc/Technology-Azure/blob/fdbc521750959868cf1ff6c93230e6220ba8ab70/extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSink.java#L58-L65

The behavior was reported in test addition done in by this [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc/pull/1154) PR.

### PR DESCRIPTION
**Pull request by zub4t**
## What this PR changes/adds

This PR modifies the logic to decide what will be the name of the file/s to be saved on sink side.  Now the sink side decides the name of the file/s based on the number of existing parts in a transfer and does not rely anymore in `blobPrefix`/`blobName` property.

## Why it does that
The logic was modified since the sink does not know how many files will be transferred  in a flow request. And when multiple files was transferred using the property `blobName` in the flow request it does override on sink side. But not anymore.

## Linked Issue(s)

Closes #169

### CODE REVIEW

File: extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSink.java [hunk 1]
```diff
@@ -55,22 +54,22 @@ void registerCompletedFile(String name) {
...
-
     /**
      * Writes data into an Azure storage container.
      */
+
     @Override
     protected StreamResult<Object> transferParts(List<DataSource.Part> parts) {
         for (DataSource.Part part : parts) {
-            var name = getDestinationBlobName(part.name());
+            var name =  getDestinationBlobName(part.name(), parts.size());
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSink.java:72]: nit: remove one of the whitespaces before the method name

**Review by ndr-brt — CHANGES_REQUESTED** [review]
please add a test that demonstrates the changes you provided

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkTest.java [hunk 2]
```diff
@@ -204,7 +204,47 @@ void getDestinationBlobName_shouldBeProperlyConcatenated(String blobName, String
...
+            "partName, ''  , folderName/, 1, folderName/partName",
+            "partName, ''  , folderName/, 2, folderName/partName",
+            "partName, blobName,  null, 1, blobName",
+            "partName, blobName,  null, 2, partName",
+            "partName, blobName,  '', 1, blobName",
+            "partName, blobName,  '', 2, partName",
+            "partName, '',   '', 1, partName" ,
+            "partName, '',   '', 2, partName" }
+            ,nullValues = { "null" })
+    void getDestinationBlobName_shouldDifferIfSingleOrMultipleFiles(String partName, String blobName, String folderName, int partSize, String expected) {
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkTest.java:230]: this test is too hard to read and the scope too broad, please split it for various cases based on the condition tested, e.g.:
- `shouldReturnBlobName_whenFolderNameIsNullOrEmpty`
- `shouldAppendSlashToFolderName_whenItIsMissing`
- ...

looking at the tests there's some smell here: making a method "package-private" only for testing doesn't look good, likely that behavior (define destination name) would stay better in a separate component that's injected in the `DataSink` so it can be tested separately.
Please extract it and clean up test a bit.

**Review by ndr-brt — CHANGES_REQUESTED** [review]

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkTest.java (hunk 2 above)
Comment (zub4t) [reply extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkTest.java]: Regarding extracting the logic for the destination name. I've created a new class, but I don't know if this is the most appropriate approach. Please let me know if this is exactly what you want.

**Review by ndr-brt — CHANGES_REQUESTED** [review]
my proposal was to have an "injectable" component, so that `DestinationBlobName` should be not static, have `folderName` and `blobName` as fields and the `getDestinationBlobName` should take only the `partName` and the `partsSize`.
It would be instantiated in the data sink factory and passed to the data sink.

This way you could move the tests about the way the blob name is build to that class, and in the data sink test just instantiate it as a mock and verify the collaboration

**Comment by zub4t** [comment]
> my proposal was to have an "injectable" component, so that `DestinationBlobName` should be not static, have `folderName` and `blobName` as fields and the `getDestinationBlobName` should take only the `partName` and the `partsSize`. It would be instantiated in the data sink factory and passed to the data sink.
> 
> This way you could move the tests about the way the blob name is build to that class, and in the data sink test just instantiate it as a mock and verify the collaboration

I did my best to do what you proposed  😊

File: extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    private String folderName;
+    private String blobName;
+
+    public void setBlobName(String blobName) {
+        this.blobName = blobName;
+    }
+
+    public void setFolderName(String folderName) {
+        this.folderName = folderName;
+    }
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java:29]: please note that in this way this component has a mutable state, and so it's not thread safe (because it's generated at startup and then being used by multiple `DataSink`).

Please make the component immutable and instantiate it once for every DataSink created

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+    DestinationBlobName destinationBlobName = new DestinationBlobName();
+
+    @ParameterizedTest
+    @CsvSource(value = {
+            "partName, blobName,  null, 1, blobName",
+            "partName, blobName,  null, 2, partName",
+            "partName, blobName,  '', 1, blobName",
+            "partName, blobName,  '', 2, partName",
+    }, nullValues = { "null" })
+    void shouldReturnBlobName_whenFolderNameIsNullOrEmpty(String partName, String blobName, String folderName, int partSize, String expected) {
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:32]: the name does not reflect the inputs (for case number 2 and 4 it is returning "partName", not blob name, I would split this test in two, one that verifies what happens when partSize is 1 and one with partSize greater than 1

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+    @ParameterizedTest
+    @CsvSource(value = {
+            "partName, null, folderName, 1, folderName/partName",
+            "partName, null, folderName, 2, folderName/partName",
+            "partName, ''  , folderName, 1,  folderName/partName",
+            "partName, ''  , folderName, 2,  folderName/partName",
+            "partName, null, folderName/, 1, folderName/partName",
+            "partName, null, folderName/, 2, folderName/partName",
+            "partName, ''  , folderName/, 1, folderName/partName",
+            "partName, ''  , folderName/, 2, folderName/partName",
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:47]: no need to set different partSize here because as demonstrated by the cases there's no difference by having partSize equal 1 or 2

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+    @ParameterizedTest
+    @CsvSource(value = {
+            "partName, '',   '', 1, partName",
+            "partName, '',   '', 2, partName",
+            "partName, null,   null, 1, partName",
+            "partName, null,   null, 2, partName",
+            "partName, null,   '', 1, partName",
+            "partName, null,   '', 2, partName",
+            "partName, '',   null, 1, partName",
+            "partName, '',   null, 2, partName",
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:64]: ditto

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+    @CsvSource(value = {
+            "partName, blobName,  null, 1, blobName",
+            "partName, blobName,  null, 2, partName",
+            "partName, blobName,  '', 1, blobName",
+            "partName, blobName,  '', 2, partName",
+    }, nullValues = { "null" })
+    void shouldReturnBlobName_whenFolderNameIsNullOrEmpty(String partName, String blobName, String folderName, int partSize, String expected) {
+        destinationBlobName.setBlobName(blobName);
+        destinationBlobName.setFolderName(folderName);
+        assertEquals(expected, destinationBlobName.resolve(partName, partSize));
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:35]: please use AssertJ `assertThat` style of assertion as it's using in the rest of the codebase

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+    @ParameterizedTest
+    @CsvSource(value = {
+            "partName, blobName, folderName, 2, folderName/partName",
+            "partName, blobName,  folderName/, 2,  folderName/partName",
+    }, nullValues = { "null" })
+    void shouldAppendFolderNameWithPartNameUsingSlash_whenPartSizeIsGraterThan1(String partName, String blobName, String folderName, int partSize, String expected) {
+        destinationBlobName.setBlobName(blobName);
+        destinationBlobName.setFolderName(folderName);
+        assertEquals(expected, destinationBlobName.resolve(partName, partSize));
+    }
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:93]: I think the case with the folder name not ending with a slash could be tested in a dedicated test and have all the other tests not to considerate that case, otherwise we're asserting the same behavior multiple time (not harmful at all but definitely not needed)

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkTest.java [hunk 9]
```diff
@@ -68,6 +66,8 @@ class AzureStorageDataSinkTest {
     private final String content = "Test Content";
     private final Exception exception = new TestCustomException("Test custom exception message");
     private final BlobMetadataProvider metadataProvider = new BlobMetadataProviderImpl(monitor);
+    private final DestinationBlobName destinationBlobName = new DestinationBlobName();
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkTest.java:69]: please use a mock and test collaboration, otherwise this test is an integration one, and we want to avoid them unless strictly necessary.

**Review by ndr-brt — CHANGES_REQUESTED** [review]

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 10]
```diff
@@ -0,0 +1,122 @@
...
+
+    @ParameterizedTest
+    @CsvSource(value = {
+            "partName, blobName,  folderName/, 2,  folderName/partName",
+    }, nullValues = { "null" })
+    void shouldAppendFolderNameWithPartNameUsingSlash_whenPartSizeIsGraterThanOneAndFolderNameEndsWithSlash(String partName, String blobName, String folderName, int partSize, String expected) {
+
+        DestinationBlobName destinationBlobName = new DestinationBlobName(blobName, folderName);
+        assertThat(destinationBlobName.resolve(partName, partSize)).isEqualTo(expected);
+    }
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:121]: a parameterized test with just a set of parameter is a simple test, please convert them accordingly

File: extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java [hunk 11]
```diff
@@ -0,0 +1,40 @@
+/*
+ *  Copyright (c) 2022 Microsoft Corporation
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java:2]: please verify headers, year is not correct and also company looks lite to not be the right one

File: extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactory.java [hunk 12]
```diff
@@ -74,18 +75,20 @@ public DataSink createSink(DataFlowStartMessage request) {
...
 
         return AzureStorageDataSink.Builder.newInstance()
                 .accountName(dataAddress.getStringProperty(ACCOUNT_NAME))
                 .containerName(dataAddress.getStringProperty(AzureBlobStoreSchema.CONTAINER_NAME))
-                .folderName(dataAddress.getStringProperty(AzureBlobStoreSchema.FOLDER_NAME))
-                .blobName(dataAddress.getStringProperty(AzureBlobStoreSchema.BLOB_NAME))
-                .blobPrefix(dataSourceAddress.getStringProperty(BLOB_PREFIX))
+                .destinationBlobName(destinationBlobName)
+                .folderName(folderName)
+                .blobName(blobName)
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactory.java:91]: these two parameters are now not used in the sink class, please remove them

File: extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java [hunk 13]
```diff
@@ -0,0 +1,40 @@
...
+ *  Contributors:
+ *       Marco Primo
+ *
+ */
+
+package org.eclipse.edc.connector.dataplane.azure.storage;
+
+import org.eclipse.edc.util.string.StringUtils;
+
+public class DestinationBlobName {
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java:19]: please document

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 14]
```diff
@@ -0,0 +1,122 @@
...
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class DestinationBlobNameTest {
+
+
+    @ParameterizedTest
+    @CsvSource(value = {
+            "partName, blobName,  null, 1, blobName",
+            "partName, blobName,  '', 1, blobName",
+    }, nullValues = { "null" })
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:29]: given that the changing part is only on a single field (folderName), please change this to `@ValueSource` and `@NullSource`.
Same for the other tests with the same pattern.

**Review by ndr-brt — CHANGES_REQUESTED** [review]

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java (hunk 14 above)
Comment (zub4t) [reply extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:29]: Would it be better then to separate these ParameterizedTests into two different normal tests? since one test will have the empty folder name and the other null? Because @ValueSource will  only need to have a parameter which is the parameter with an empty string and then I would have to use another test to use the @NullSource annotation

Comment (zub4t) [reply extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:29]: Something like 

```
    @Test
    void shouldReturnBlobName_whenFolderNameIsEmptyAndPartSizeIsEqualToOne() {

        String partName="partName", blobName = "blobName",folderName="",expected="blobName";
        DestinationBlobName destinationBlobName = new DestinationBlobName(blobName, folderName);
        assertThat(destinationBlobName.resolve(partName, 1)).isEqualTo(expected);
    }
    @Test
    void shouldReturnBlobName_whenFolderNameIsNullAndPartSizeIsEqualToOne() {

        String partName="partName", blobName = "blobName",folderName=null,expected="blobName";
        DestinationBlobName destinationBlobName = new DestinationBlobName(blobName, folderName);
        assertThat(destinationBlobName.resolve(partName, 1)).isEqualTo(expected);
    }
```

Comment (ndr-brt) [reply extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java]: you can use `ValueSource` and `NullSource` in the same test, anyway I think separated tests are better in any case.
Just a thought: testing the "null" case is not really needed, because should be implicit with the "empty" one, as the code should always be null-safe and the language offers easy ways to ensure that (e.g. `Optional`)

**Review by ndr-brt — APPROVED** [review]

File: extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java [hunk 15]
```diff
@@ -0,0 +1,69 @@
...
+
+import java.util.Optional;
+
+/**
+ * Utility class responsible for determining the name under which a file will be saved.
+ */
+public class DestinationBlobName {
+
+    private final Optional<String> folderName;
+    private final Optional<String> blobName;
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java:27]: please do not use `Optional` as class field, it's not a good practice, wrap the field with `Optional` when you need to evaluate it (in the `resolve` method)

File: extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java [hunk 16]
```diff
@@ -75,51 +54,29 @@ void shouldAppendFolderNameWithPartNameUsingSlash_whenBlobNameIsEmpty() {
...
     @Test
-    void shouldAppendFolderNameWithPartNameUsingSlash_whenBlobNameIsNullAndFolderNameEndsWithSlash() {
+    void shouldAppendFolderNameWithPartNameUsingSlash_whenBlobNameIsEmptyAndFolderNameEndsWithSlash() {
 
         var partName = "partName";
+        var blobName = "";
         var folderName = "folderName/";
         var expected = "folderName/partName";
-        DestinationBlobName destinationBlobName = new DestinationBlobName(null, folderName);
+        DestinationBlobName destinationBlobName = new DestinationBlobName(blobName, folderName);
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/test/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobNameTest.java:65]: please use `var` whenever possible, same for the other tests

File: extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java [hunk 17]
```diff
@@ -16,34 +16,53 @@
...
+            }
         }
-        return name;
+        if (partsSize == 1 && blobName.isPresent() && !blobName.get().isBlank()) {
+            sb.append(blobName.get());
+        } else {
+            sb.append(partName);
+        }
+
+        return sb.toString();
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/DestinationBlobName.java:65]: apart from the "optional" thing I don't understand why to add such complexity in this method.
`Optional` can be used only if it make things easier, but in this case `isNullOrEmpty` already did the job quite well, so there's no real need to change the previous implementation.

**Review by ndr-brt — CHANGES_REQUESTED** [review]

**Review by ndr-brt — APPROVED** [review]
LGTM
